<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Revenue By Customer Query</title>
	</head>
	
	<body>
	<%
    
	try {

		//Get the database connection.
		ApplicationDB db = new ApplicationDB();	
		Connection con = db.getConnection();		


		String customer = request.getParameter("customers");
		String[] customerInfo = customer.split(" ");
		String firstName = customerInfo[0];
		String lastName = customerInfo[1];
		String email = customerInfo[2].substring(1, customerInfo[2].length()-1);
		
		//Create a SQL statement.
		PreparedStatement ps = con.prepareStatement("select c.username, sum(r.total_fare) as total_revenue from customers c join reservations r on c.username = r.username where c.email_address = ? group by c.username, c.email_address;");
		//Replace "?" with value entered in textboxes.
		ps.setString(1, email);
		//Run the query against the database.
		ResultSet result = ps.executeQuery();
		
		if(!result.isBeforeFirst()){
			request.setAttribute("customerRevenue", "Total Revenue Generated by "+firstName+" "+lastName+": $0.00");
	        request.getRequestDispatcher("admin_access.jsp#customer-functions").include(request, response);
		}
		else if(result.next()){
			String total = result.getString("total_revenue");
			request.setAttribute("customerRevenue", "Total Revenue Generated by "+firstName+" "+lastName+": $"+total);
	        request.getRequestDispatcher("admin_access.jsp#customer-functions").include(request, response);
		}
				
		//Close the connection.
		db.closeConnection(con);
	} catch (Exception e) {
		out.print(e);
	}
	
	%>
	</body>
</html>