<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Revenue By Transit Line Query</title>
	</head>
	
	<body>
		<%
    
	try {

		//Get the database connection.
		ApplicationDB db = new ApplicationDB();	
		Connection con = db.getConnection();		

		String lineName = request.getParameter("transit_lines");
		
		//Create a SQL statement.
		PreparedStatement ps = con.prepareStatement("select b.line_name, sum(r.total_fare) as total_revenue from books b join reservations r on b.r_number = r.r_number where b.line_name = ? group by b.line_name;");
		//Replace "?" with value entered in textboxes.
		ps.setString(1, lineName);
		//Run the query against the database.
		ResultSet result = ps.executeQuery();
		
		if(!result.isBeforeFirst()){
			request.setAttribute("lineRevenue", "Total Revenue Generated by "+lineName+": $0.00");
	        request.getRequestDispatcher("admin_access.jsp#line-functions").include(request, response);
		}
		else if(result.next()){
			String total = result.getString("total_revenue");
			request.setAttribute("lineRevenue", "Total Revenue Generated by "+lineName+": $"+total);
	        request.getRequestDispatcher("admin_access.jsp#line-functions").include(request, response);
		}
				
		//Close the connection.
		db.closeConnection(con);
	} catch (Exception e) {
		out.print(e);
	}
	
	%>
	</body>
</html>